# Generated by Django 3.1.6 on 2021-02-13 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='not defined!', max_length=200)),
                ('city', models.CharField(default='not defined!', max_length=200)),
                ('state', models.CharField(default='not defined!', max_length=200)),
                ('zipcode', models.CharField(default='not defined!', max_length=200)),
                ('date_added', models.DateTimeField()),
                ('order', models.ForeignKey(default='not defined!', null=True, on_delete=django.db.models.deletion.PROTECT, to='main.order')),
                ('shipping_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.shippingaddress')),
            ],
        ),
    ]
